name: Build and deploy .NET Core app to Azure Web App

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Install EF Core CLI
        run: |
          dotnet tool install --global dotnet-ef
          dotnet tool restore
          export PATH="$PATH:$HOME/.dotnet/tools"
          dotnet ef --version

      - name: Build with dotnet
        run: dotnet build --configuration Release InventoryTrackApi.csproj

      - name: dotnet publish
        run: dotnet publish InventoryTrackApi.csproj -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Install EF Core CLI
        run: |
          dotnet tool install --global dotnet-ef
          dotnet tool restore
          export PATH="$PATH:$HOME/.dotnet/tools"
          dotnet ef --version

      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Apply database migrations
        run: |
          export PATH="$PATH:$HOME/.dotnet/tools"
          dotnet ef database update --project InventoryTrackApi.csproj
        env:
          DB_CONNECTION_STRING: ${{ secrets.DB_CONNECTION_STRING }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'InventoryApi'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .
